#+TITLE: CalibrePluginScaleATon

* CalibrePluginScaleATon

A skeleton that "tries" to be a basis for practical calibre plugin creation.

* memo

  github's org-mode renderer will not render this correctly!

** where we are

   #+begin_src sh :eval never
   lsb_release -a
   #+end_src

   #+RESULTS:
   | Distributor ID: | Ubuntu             |
   | Description:    | Ubuntu 12.04.1 LTS |
   | Release:        | 12.04              |
   | Codename:       | precise            |


   #+begin_src sh :results output :eval never
   calibredb --version
   #+end_src

   #+RESULTS:
   : calibredb (calibre 0.9.11)

   #+begin_src sh :results output
   python -c 'import sys; print sys.version_info'
   #+end_src

   #+RESULTS:
   : sys.version_info(major=2, minor=7, micro=3, releaselevel='final', serial=0)

** where we want to go

   - add a menu entry to right click that says "Get info"
   - when you click it, it prints the dict of the book entry
     
** version 1

   ref: http://manual.calibre-ebook.com/creating_plugins.html

   first code in the tutorial involves importing calibre:

   #+begin_src python :eval never
     import os
     from calibre.customize import FileTypePlugin
   #+end_src

   #+RESULTS:
   : Traceback (most recent call last):
   :   File "<stdin>", line 7, in <module>
   :   File "<stdin>", line 4, in main
   : ImportError: No module named calibre.customize
   
   So we need to set up calibre as an importable module...

*** set up our development environment

    ref: http://manual.calibre-ebook.com/develop.html

**** set up a virtualenv

     #+begin_src sh :eval never
     virtualenv venv
     #+end_src

     #+RESULTS:
     : New python executable in venv/bin/python
     : Installing setuptools............done.
     : Installing pip...............done.

**** get calibre src for python import

     make sure we have a copy of the bazaar code somewhere. skipping this part -- you want to follow develop.html linked above.

     mine is sitting in =~/dev/calibre/calibre-src=; make sure you run =bzr merge= to update it.

     #+begin_src sh :results output :eval never
     grep -n numeric_version ~/dev/calibre/calibre-src/src/calibre/constants.py
     #+end_src

     #+RESULTS:
     : 7:numeric_version = (0, 9, 11)
     : 8:__version__   = u'.'.join(map(unicode, numeric_version))

**** =.pth= file hacks for calibre import

     #+begin_src sh :results output :eval never
     cat venv/lib/python2.7/site-packages/calibre.pth
     #+end_src

     #+RESULTS:
     : import os, sys; sys.path.append(os.path.expanduser("~/dev/calibre/calibre-src/src"))
     : import os, sys; sys.resources_location = os.path.expanduser("~/dev/calibre/calibre-src/resources")
     : import os, sys; sys.extensions_location = os.path.abspath("~/dev/calibre/calibre-src/src/calibre/plugins")
     : import sys; sys.executables_location = "/usr/bin"

     now attempt import calibre

     #+begin_src sh :results output
     . venv/bin/activate
     python -c 'import calibre'
     #+end_src

     #+RESULTS:
     : Loading ICU failed with:  No module named icu
     : Loading ICU failed with:  No module named icu

